INSERT INTO   MEMBERS 
( EMAIL , PWD , FREQ, STATE )
VALUES ('hong@test.com','1111',300,1);

INSERT INTO   MEMBERS 
( EMAIL , PWD , FREQ, STATE )
VALUES ('kim@test.com','2222',600,0);


INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (1,'지난 겨울 나만의 서울 여행', '2013-1-1');

INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (1,'지난 여름 나만의 런던 여행', '2013-6-1');

INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (2,'지난 봄 나만의 도쿄 여행', '2012-3-1');

INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (2,'지난 가을 나만의 부산 여행', '2012-9-1');


INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (1, 37.553163, 126.972662, '2013-1-1', 1);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (1, 37.558642, 126.978251, '2013-1-1', 0);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (1, 37.553758, 126.980975, '2013-1-1', 1);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (1, 37.565455, 126.977160, '2013-1-1', 0);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (1, 37.576023, 126.976943, '2013-1-1', 1);


INSERT INTO   LOCATIONS 
( PNO , TITLE , DISCRIPTION)
VALUES (1,'서울역','장소내용을 입력하세요');


INSERT INTO   LOCATIONS 
( PNO ,TITLE , DISCRIPTION)
VALUES (3,'남산','장소내용을 입력하세요');


INSERT INTO   LOCATIONS 
( PNO ,TITLE , DISCRIPTION)
VALUES (5,'광화문','장소내용을 입력하세요');


INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (2, 51.505065, -0.086019, '2013-6-1', 1);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (2, 51.516494, -0.130436, '2013-6-1', 0);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (2, 51.531126, -0.157129, '2013-6-1', 1);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (2, 51.456808, -0.194325, '2013-6-1', 0);

INSERT INTO   POINTS 
( CNO , LAT , LNG , PDATE , STATE)
VALUES (2, 51.431237, -0.187545, '2013-6-1', 1);


INSERT INTO   LOCATIONS 
( PNO , TITLE , DISCRIPTION)
VALUES (6,'런던역','장소내용을 입력하세요');


INSERT INTO   LOCATIONS 
( PNO ,TITLE , DISCRIPTION)
VALUES (8,'런던 동물원','장소내용을 입력하세요');


INSERT INTO   LOCATIONS 
( PNO ,TITLE , DISCRIPTION)
VALUES (10,'윔블던 스타디움','장소내용을 입력하세요');


select * from POINTS;

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (1,0);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (2,1);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (3,0);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (4,1);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (6,0);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (7,1);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (8,0);

INSERT INTO   TRANSPORTS 
( PNO ,STATE )
VALUES (9,1);


INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (1,'p1');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (1,'p2');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (1,'p3');


INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (2,'p4');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (2,'p5');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (2,'p6');


INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (3,'p7');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (3,'p8');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (3,'p9');


INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (4,'p10');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (4,'p11');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (4,'p12');


INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (5,'p13');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (5,'p14');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (5,'p15');


INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (6,'p16');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (6,'p17');

INSERT INTO   PHOTOS 
( LNO ,PATH )
VALUES (6,'p18');







