INSERT INTO   MEMBERS 
( EMAIL , PWD , FREQ, STATE )
VALUES ('hong@test.com','1111',300,1);

INSERT INTO   MEMBERS 
( EMAIL , PWD , FREQ, STATE )
VALUES ('kim@test.com','2222',600,0);


INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (1,'지난 겨울 나만의 서울 여행', '2013-1-1');

INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (1,'지난 여름 나만의 런던 여행', '2013-6-1');


INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (2,'지난 봄 나만의 도쿄 여행', '2012-3-1');

INSERT INTO   CONTENTS 
( MNO , TITLE , CDATE)
VALUES (2,'지난 가을 나만의 부산 여행', '2012-9-1');




INSERT INTO   POINTS 
( PNO , DISCRIPTION , PATH )
VALUES ('임꺽정','2','222-2222','1111');


INSERT INTO   PHOTOS 
( PNO , DISCRIPTION , PATH )
VALUES ('임꺽정','2','222-2222','1111');